# fly.toml app configuration file generated for gregemyers-api-fly on 2023-05-20T22:33:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gregemyers-api-fly"
primary_region = "lhr"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
